# https://www.springcloud.io/post/2022-05/springboot-3-0/#multi-document-yaml

# Shared profile ====================================================================================O

password:
  validation:
    needs-mixed-case: true
    minimum-length: 7
    maximum-length: 21
    needs-special-characters: true
    needs-numbers: true
    needs-letters: true

first-name:
  validation:
    minimum-length: 2
    maximum-length: 32

jwt:
  life-in-milliseconds: 6000000

username:
  validation:
    minimum-length: 3
    maximum-length: 32

last-name:
  validation:
    minimum-length: 2
    maximum-length: 256
    
location:
  name:
    validation:
      minimum-length: 2
      maximum-length: 32
  instruction:
    validation:
      minimum-length: 0
      maximum-length: 4096

company:
  email: en@gmail.com
  address: EN, Off Baboon Crescent, Kibiko, Nairobi, Kenya
  website: greenzone.org
  company: GreenZone
  phone: +254 (0) 758 921 932
      
---

# EN PROFILE =======================================================================================

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type: INFO
      springframework:
        security: INFO

superadmin:
  allow-restart: true

email:
  disabled: false
  do-not-reply: no.reply@green-zone.org
  host: sandbox.smtp.mailtrap.io
  tls: no
  ssl: yes
  port: 587
  protocol: smtp
  username: 9abc6f55dcbbca
  password: af53524090bdbe

jwt:
  life-in-milliseconds: 3600000

spring:
  config:
    activate:
      on-profile: "en"
  datasource:
    url: jdbc:postgresql://localhost:5432/greenzonedev
    username: postgres
    password: eli123
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20  # Optional: for batch insert optimization
        order_inserts: true
        order_updates: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  sql:
    init:
      data-locations: 
        - classpath:sql/standing_data.sql
        - classpath:sql/other_data_en.sql
      mode: always

web:
  server:
    port: 3001
    protocol: http
    domain: localhost

management:
  endpoints:
    web:
      exposure:
        include: 
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always